name: Package Management System
description: File documentation and requirements
title: "[PkgMgmt]: "
labels: ["pkgmgmt"]
body:
  - type: textarea
    attributes:
      label: "Describe the package management system"
      description: "Try to describe your package management system as well as you can, as that will help with speeding up onboarding"
  - type: textarea
    attributes:
      label: "Package management system query tools"
      description: "Try to describe tools used to query your package management system with examples if possible"
  - type: textarea
    attributes:
      label: "References"
      description: "List package management design, schemas, documentation, etc"
  - type: textarea
    attributes:
      label: "Provenance"
      description: "A brief summary of how you are solving the software provenance"
  - type: textarea
    attributes:
      label: "Will to adopt WG recommendations?"
      description: "yes/no and a brief summary in support of your preference"