on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Register SCITT Signed Statement
    steps:
      - name: test
        shell: bash
        run: |
          echo ${{ GITHUB_REPOSITORY }}
          echo ${{ GITHUB_REPOSITORY }} + "foo"
          echo "$GITHUB_REPOSITORY:$GITHUB_SHA"
