on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Register SCITT Signed Statement
    steps:
      - name: test
        shell: bash
        run: |
          echo ${{ github.repository }}
          echo ${{ github.repository }}  "foo"
          echo "${{ github.repository }}:${{ github.sha }}"
