on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Register SCITT Signed Statement
    steps:
      - name: Register SCITT Signed Statement
        id: register-scitt-signed-statement
        uses: datatrails/scitt-action@v0.3.7.3
        with:
          scitt-client_id: ${{ secrets.DATATRAILS_CLIENT_ID }}
          scitt-secret: ${{ secrets.DATATRAILS_SECRET }}
          feed: "my-project-v0.1"
          signed-statement-file: "signed-statement.sbom"
          signing-key-file: "synsation.pem"
          issuer: "synsation.io"
          output-file: "receipt.cbor"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
